### ISSUE TITLE
Invalid query selector error

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/chart-module-countryRankingStrips#1]
Getting this:

![image](https://user-images.githubusercontent.com/2772078/88456368-152d3080-ce75-11ea-8569-b15cb22b7954.png)

Here is how I've configured the chart:

![image](https://user-images.githubusercontent.com/2772078/88456378-2d9d4b00-ce75-11ea-9e7d-ed9cddef0c68.png)

**Comment by hobbes7878** [comment]
Believe that's this line: https://github.com/reuters-graphics/chart-module-countryRankingStrips/blob/master/src/lib/chart.js#L354

Which is problematic, because you're assuming this chart will have an _id_, but generally we give them a _class_ so we can use them as small multiples.

**Comment by hobbes7878** [comment]
Yeah, there are a few of these.

As a general rule, you shouldn't ever use `d3.select` nakedly in your code. Always use `this.selection()` from the module so your selections are always bound to the scope of the module.

So you should rewrite a line like this:

```javascript 
d3.select(`#${node.id} .CountryRankingStrips .axis.axis-x`).classed('customAxisFormat', 'true');
```

to this...


```javascript
this.selection().select('.CountryRankingStrips .axis.axis-x').classed('customAxisFormat', 'true');
```

**Comment by pkd2512** [comment]
Resolved.
