### ISSUE TITLE
Highlight strip is not in correct position

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/chart-module-countryRankingStrips#2]
![image](https://user-images.githubusercontent.com/2772078/88456745-2f1c4280-ce78-11ea-9865-8047da7c8288.png)

It appears to _start_ in the right position as I reload the page, but when the component re-renders with new data, it goes to 0 or whatever the min is.

**Comment by pkd2512** [comment]
![image](https://user-images.githubusercontent.com/7580745/88457335-1c6b3300-cea3-11ea-8d2c-c4e78fa9e062.png)
![image](https://user-images.githubusercontent.com/7580745/88457421-cd71cd80-cea3-11ea-8ea9-ecf184bd7acd.png)

```RESOLVED``` 
appendSelect was not bound to data-key, so they were getting updated randomly.
